### PR TITLE
Expose Test attribute for BidRequest

### PR DESCRIPTION
**Pull request by justuswilhelm**
See 3.2.1 Object: BidRequest, attribute `test`

### CODE REVIEW

**Comment by dolzenko** [comment]
LGTM. @dim looks fine to merge

**Comment by justuswilhelm** [comment]
@dolzenko Thanks!

**Comment by dim** [comment]
@justuswilhelm thanks

**Comment by justuswilhelm** [comment]
Thank you @dim 👍

**Comment by justuswilhelm** [comment]
It seems like the CI is having some problems with my commit f6d39e9. See here https://travis-ci.org/bsm/openrtb/builds/154109978

screen shot 2016-08-22 at 12 39 08 pm

Is there anything I can do to help?

**Comment by dim** [comment]
Should be fixed, thanks

**Pull request merged**
